version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - node_modules-data:/home/tvgni/app/node_modules
    command: [ "npm", "run", "dev" ]

volumes:
  node_modules-data:
