import './theme/dx.material.traderacademic.css';
import './globals.css';
import React from 'react';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import MenuLeft from './dashboard/navigations';
import { user } from '@/utils/auth0.page';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const userSession = await user();
  return (
    <html lang="en">
      <UserProvider>
        <body className={'dx-viewport'}>
          {userSession.isAuthenticated ? (
            <MenuLeft session={userSession}>{children}</MenuLeft>
          ) : (
            children
          )}
        </body>
      </UserProvider>
    </html>
  );
}
