import './globals.css';
import 'devextreme/dist/css/dx.material.blue.light.css';
import React from 'react';
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={'dx-viewport'}>{children}</body>
      </UserProvider>
    </html>
  );
}
