import React from 'react';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import './theme/dx.material.traderacademic.css';
import './globals.css';
import MenuLeft from './dashboard/navigations';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={'dx-viewport'}>
          <MenuLeft>{children}</MenuLeft>
          <div id="containerElement"></div>
        </body>
      </UserProvider>
    </html>
  );
}
